accounts/urls.py
from django.urls import path
# ビューをインポート
from . import views
# ログイン専用のビューをインポート()
from django.contrib.auth import views as auth_views

# 逆引きの設定
app_name = 'accounts'

urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/', views.SignupView.as_view(), name='signup'),

    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),

    # ログインページの表示
    # 「http(s)://<ホスト名>/login/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.LogoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

article/urls.py
from django.urls import path
# ビューをインポート
from . import views

# 逆引きの設定
app_name = 'article'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreateArticleView.as_view(), name='post'),
    path('post_success/', views.ArticleSuccessView.as_view(), name='post_done'),
    path('article/<int:category>/', views.CategoryView.as_view(), name='article_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('article-detail/<int:pk>/', views.DetailView.as_view(), name='article_detail'),
    path('mypage/', views.MypageView.as_view(), name = 'mypage'), 
    path('article-delete/<int:pk>/',views.ArticleDeleteView.as_view(),name = 'article_delete'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

newsproject/urls.py
from django.contrib import admin
from django.urls import include, path
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views
# settingsを追加
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('', include('accounts.urls')),

    # パスワードリセットのためのURLパターン
    # メアドに送られるとURLとなる
    # 毎回異なり、自動生成され一回限り有効なURL(Djangoの機能を使用する)
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"),name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"),name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"),name ='password_reset_complete'),
]

urlpatterns += static(

    settings.MEDIA_URL,

    document_root=settings.MEDIA_ROOT
)

article/models.py
from django.db import models
# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser

# classモデル(DB)を定義　⇒ モデルを継承
class Category(models.Model):
    '''投稿する写真のカテゴリを管理するモデル
    '''
    # カテゴリ名のフィールド
    title = models.CharField(
        verbose_name='カテゴリ', # フィールドのタイトル
        max_length=20)
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        
        Returns(str):カテゴリ名
        '''
        return self.title

class ArticlePost(models.Model):
    '''投稿されたデータを管理するモデル
    '''

    # ユーザーは、CustomUserモデルを参照(外部キー)
    # models.ForeignKey(CustomUser...)が外部キーの定義
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='ユーザー',
        # ユーザーを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )
    # Categoryモデル(のtitle)とPhotoPostモデルを
    # 1対多の関係で結び付ける
    # Categoryが親でPhotoPostが子の関係となる
    category = models.ForeignKey(
        Category,
        # フィールドのタイトル
        verbose_name='カテゴリ',
        # カテゴリに関連付けられた投稿データが存在する場合は
        # そのカテゴリを削除できないようにする
        on_delete=models.PROTECT
        )
    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル', # フィールドのタイトル
        max_length=200        # 最大文字数は200
        )
    # コメント用のフィールド
    comment = models.TextField(
        verbose_name='コメント',  # フィールドのタイトル
        )
    # ImageFieldは画像を保存するフィールド
    image1 = models.ImageField(
        verbose_name='イメージ1',# フィールドのタイトル
        # Photosフォルダに保存
        upload_to = 'photos'   # MEDIA_ROOT以下のphotosにファイルを保存  
        )
    # イメージのフィールド2
    image2 = models.ImageField(
        verbose_name='イメージ2',# フィールドのタイトル
        upload_to = 'photos',  # MEDIA_ROOT以下のphotosにファイルを保存
        blank=True,            # フィールド値の設定は必須でない
        null=True              # データベースにnullが保存されることを許容
        )
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時', # フィールドのタイトル
        auto_now_add=True       # 日時を自動追加
        )
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        
        Returns(str):投稿記事のタイトル
        '''
        return self.title

article/forms.py
from django.forms import ModelForm
from .models import ArticlePost
from django import forms

class ArticlePostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス
        
        Attributes:
          model: モデルのクラス
          fields: フォームで使用するモデルのフィールドを指定
        '''
        model = ArticlePost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

class ContactForm(forms.Form):
    # HTML側のデータを取得
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    message = forms.CharField(label= 'メッセージ', widget=forms.Textarea)

    # __init__メソッド ⇒ 初期化メソッド
    def __init__(self, *args, **kwargs):

        
        super(). __init__(*args, **kwargs)
        #name フィールドのplaceholderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = \
        'お名前を入力してください'
        #name フィールドを出力する <input>タグのclass 属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'

        # email フィールドのplaceholderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = \
        'メールアドレスを入力してください'
        #email フィールドを出力する <input > タグのclass 属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'

        # message フィールドのplaceholderにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = \
        'メッセージを入力してください'
        # message フィールドを出力する <input> タグのclass 属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'

article/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import ArticlePostForm
from .models import ArticlePost
from django.views.generic import FormView
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage

class IndexView(ListView):
    """トップページのビュー"""
    template_name = 'index.html'
    queryset = ArticlePost.objects.order_by('-posted_at') 
    paginate_by = 9
    

class ContactView(FormView):
    template_name = "contact.html"
    form_class = ContactForm
    success_url = reverse_lazy('article:contact')

    def form_valid(self, form):
        # フォームに入力されたデータをフィールド名を指定して取得
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']


        # フォームの入力データの書式を設定
        ### 本文 ###
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ: {2}\n '.format(name, email, message)

        # 送信元のメールアドレス
        from_email = 'admin@example.com'
        # 送信先のメールアドレス
        to_email = ['admin@example.com']

        ### ↑↑ 送信するための準備完了 ### 
        
        # EmailMessage オブジェクトを生成
        message = EmailMessage(body=message, from_email=from_email, to=to_email)
        # メッセージを送信(上記で作成したオブジェクトのメソッドを呼び出し)
        message.send()

        # 送信完了後に表示するメッセージ
        messages.success(self.request, 'お問い合わせは正常に送信されました。')

        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class CreateArticleView(CreateView):
    """ニュース記事投稿ページのビュー"""
    form_class = ArticlePostForm
    template_name = "post_article.html"
    success_url = reverse_lazy('article:post_done')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

class ArticleSuccessView(TemplateView):
    """投稿完了ページのビュー"""
    template_name = 'post_success.html'

class CategoryView(ListView):
    """カテゴリごとの記事一覧ページのビュー"""
    template_name = 'index.html'  
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs['category'] 

        return ArticlePost.objects.filter(category=category_id).order_by('-posted_at')

class UserView(ListView):
    '''ユーザーの投稿一覧ページのビュー

    Attributes:
    template_name: レンダリングするテンプレート
    paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
        '''クエリを実行する

        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する

        Returns:
        クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # userキーの値(ユーザーテーブルのid)を取得
        user_id = self.kwargs['user']
        # filter(フィールド名=id)で絞り込む
        user_list = ArticlePost.objects.filter(
            user=user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list

class MypageView(ListView):
    # HTMLを指定
    template_name ='mypage.html'
    # ページネーションを指定(9)
    paginate_by = 9

    def get_queryset(self):
        # ログインしているユーザで絞込
        # PhotoPostモデルから
        queryset = ArticlePost.objects.filter(user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset

class DetailView(DetailView):
    """記事の詳細表示ビュー"""
    template_name = 'detail.html'
    model = ArticlePost

@method_decorator(login_required, name='dispatch')
class MypageView(ListView):
    """マイページのビュー"""
    template_name = 'mypage.html'

    def get_queryset(self):
        return ArticlePost.objects.filter(user=self.request.user).order_by('-posted_at')

@method_decorator(login_required, name='dispatch')
class ArticleDeleteView(DeleteView):
    """記事削除のビュー"""
    model = ArticlePost
    template_name = 'article_delete.html'
    success_url = reverse_lazy('article:mypage')

article/templates/article_delete.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Article Detail{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'article:article_detail' object.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

article/templates/article_list.html
  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- レコードが格納されたobject_listからレコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}
        <!-- 列要素を配置 -->
        <div class="col">
          <div class="card shadow-sm">
            <!-- svgタグをimgに変更src属性を追加して1枚目のイメージのURLを設定 -->
            <img src="{{ record.image1.url }}"
                class="bd-placeholder-img card-img-top"
                width="100%" height="225"
                xmlns="http://www.w3.org/2000/svg"
                role="img" aria-label="Placeholder: Thumbnail"
                preserveAspectRatio="xMidYMid slice"
                focusable="false">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"/>
            </img>
            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <p class="card-text">
                <!-- titleフィールドを出力 -->
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <!-- 詳細ページを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'article:article_detail' record.pk %}'">
                          見てみる</button>
                  <!-- カテゴリを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'article:article_cat' category=record.category.id %}'">
                          {{record.category.title}}</button>
                </div>
                <!-- 投稿したユーザー名を出力-->
                <a href="{% url 'article:user_list' user=record.user.id %}">
                  <small class="text-muted">
                    {{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
        <!-- forブロック終了 -->
        {% endfor %}
      <!-- 行要素ここまで -->
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

article/templates/article_title.html
  <!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">この世の闇ニュース</h1>
        <p class="lead text-muted">
          記事を見て反社会的勢力に思いを馳せましょう。
          素敵なニュースをお待ちしています。</p>
        <p>
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <a href="{% url "article:post" %}"
            class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}"
            class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'accounts:signup' %}"
            class="btn btn-primary my-2">サインアップ</a>
          <a href="{% url 'accounts:login' %}"
            class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

article/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>
    
    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
　　        href={% static 'assets/favicon.ico' %} />
　　  
    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link href="{% static 'css/styles123.css' %}" rel="stylesheet" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">この世の知らないことが知れます</h4>
              <p class="text-muted">
                誰でも参加できる闇ニュース投稿サイトです。<br>
                自分で見つけたニュースならなんでも大丈夫です。<br>
                でも、カテゴリに属するニュースに限ります。
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'article:mypage' %}"
                       class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                       class="text-white">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                <li><a href="{% url 'article:contact' %}"
                       class="text-white">お問い合わせ</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                <li><a href="{% url 'article:contact' %}"
                       class="text-white">お問い合わせ</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'article:index' %}"
             class="navbar-brand d-flex align-items-center">
             <svg 
             xmlns="http://www.w3.org/2000/svg" 
             width="24" height="30" 
             fill="none" 
             stroke="currentColor" 
             stroke-linecap="square" 
             stroke-linejoin="miter" 
             stroke-width="1.5" 
             viewBox="0 0 24 36" 
             aria-hidden="true" 
             class="news-icon">
           <!-- 新聞の外枠 -->
           <rect x="2" y="2" width="20" height="32" stroke="currentColor"/>
         
           <!-- 見出し部分 -->
           <rect x="4" y="4" width="16" height="3" fill="currentColor"/>
         
           <!-- 横線 (記事内容) -->
           <line x1="4" y1="10" x2="20" y2="10" />
           <line x1="4" y1="12" x2="20" y2="12" />
           <line x1="4" y1="14" x2="16" y2="14" />
           <line x1="4" y1="16" x2="16" y2="16" />
         
           <!-- サムネイル (小さい四角形) -->
           <rect x="4" y="20" width="8" height="6" stroke="currentColor" />
         </svg>
         
         
            <!-- リンクテキスト-->
            <strong>この世の闇ニュース</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    {% block footer %}
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url "article:index" %}">トップへ戻る</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          この世の闇ニュース &copy; </p>
      </div>
    </footer>
    {% endblock %}
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

article/templates/detail.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Article Detail{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる-->
          <div class="col offset-3">
            <!-- タイトル -->
            <h2>{{object.title}}</h2>
            <!-- コメント -->
            <p>{{object.comment}}</p>
            <br>
            <!-- 投稿日時 -->
            <p>{{object.posted_at}}に投稿</p>
            <!-- 1枚目の写真 -->
            <p><img src="{{ object.image1.url }}"></img></p>
            <!-- 2枚目の写真が投稿されていたら表示する-->
            {% if object.image2 %}
              <p><img src="{{ object.image2.url }}"></img></p>
            {% endif %}
            
            <!-- 投稿写真がログイン中のユーザーのものであれば削除ボタンを表示-->
            {% if request.user == object.user %}
            <form method="POST">
            <!-- リンク先のURL
                 article/<Article postsテーブルのid値>/delete/-->
            <a href="{% url 'article:article_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
            
            
          </dv>
        </dv>
      </dv>
      {% endblock %}

article/templates/index.html
{% extends "base.html" %}

{% block title %}この世の闇ニュース{% endblock %}

{% block contents %}
<!-- タイトルテンプレートの組み込み-->
{% include "article_title.html" %}

<!-- 投稿一覧テンプレートの組み込み-->
{% include "article_list.html" %}

<!-- ページネーションの組み込み -->
{% include "pagination.html" %}

{% endblock %}

article/templates/mypage.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Mypage{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートは組み込まない-->
      
      <!-- ユーザーの投稿件数を表示-->
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}さんのマイページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
            <p>投稿<strong>{{object_list.count}}</strong>件</p>
          {% endif %}
          <a href="{% url 'article:post' %}">投稿する</a>
        </div>
        <hr>
      {% endif %}
      
      <!-- 投稿一覧テンプレートの組み込み-->
      {% include "article_list.html" %}
        
      <!-- ページネーションの組み込み-->
      {% include "pagination.html" %}

      {% endblock %}

article/templates/pagination.html
<!-- ページネーションのアイコンを左右中央に配置 -->
<ul class="pagination"
    style="justify-content:center">
    <!--
    前ページを表示するアイコンとリンクの設定
    ページネーションされたPageオブジェクトをorderby_recordsで取得
    Page.has_previous: 直前にページがある場合にTrueを返す
    -->
    {% if page_obj.has_previous %}
    <!--
    前のページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示
    Page.previous_page_number: 直前のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link"
        　　 href="?page={{ page_obj.previous_page_number }}"
        　　 aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--
     すべてのページについてページ番号のアイコンを表示
     paginator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す
     page_obj.paginator.page_rangeとして取得
     ブロックパラメーターnumに順次取り出される
    -->
    {% for num in page_obj.paginator.page_range %}
        <!--
        各ページのアイコンを出力
        Page.number: 引き渡されたページのページ番号を返す
        -->
        {% if page_obj.number == num %}
        <!--
        処理中のページ番号が引き渡されたページのページ番号と一致する場合は
        ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)
        -->
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        <!--
        ページ番号が引き渡されたページのページ番号と一致しない場合
        -->
        {% else %}
        <!--
        ページ番号のアイコン(アクティブ状態ではない)にリンクを設定して表示
        -->
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    <!--
    次ページへのリンクを示すアイコンの表示
    Page.has_next: 次のページがある場合にTrueを返す
    -->
    {% if page_obj.has_next %}
    <!--
    次ページが存在する場合はリンクを設定したアイコン［>>]を表示
    Page.next_page_number: 次のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>